// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthorizeService.proto

package com.rrkj.flour.authorize.api;

public final class AuthorizeServiceProto {
  private AuthorizeServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TPermission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TPermission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TRole_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TRole_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TIdAndString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TIdAndString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListTPermission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListTPermission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListTRole_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListTRole_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026AuthorizeService.proto\"\226\001\n\013TPermission" +
      "\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\r\n\005ptype\030\003 \001(" +
      "\t\022\022\n\npermission\030\004 \001(\t\022\r\n\005label\030\005 \001(\t\022\r\n\005" +
      "descr\030\006 \001(\t\022\r\n\005utime\030\007 \001(\003\022\r\n\005ctime\030\010 \001(" +
      "\003\022\016\n\006status\030\t \001(\005\"\212\001\n\005TRole\022\n\n\002id\030\001 \001(\003\022" +
      "\014\n\004name\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022\014\n\004icon\030\004 \001" +
      "(\t\022\r\n\005label\030\005 \001(\t\022\r\n\005descr\030\006 \001(\t\022\r\n\005utim" +
      "e\030\007 \001(\003\022\r\n\005ctime\030\010 \001(\003\022\016\n\006status\030\t \001(\005\"\021" +
      "\n\003TId\022\n\n\002id\030\001 \001(\003\"\'\n\014TIdAndString\022\n\n\002id\030" +
      "\001 \001(\003\022\013\n\003str\030\002 \001(\t\"-\n\017ListTPermission\022\032\n" +
      "\004list\030\001 \003(\0132\014.TPermission\"!\n\tListTRole\022\024" +
      "\n\004list\030\001 \003(\0132\006.TRole2\266\001\n\025PermissionGrpcS" +
      "ervice\022!\n\tqueryById\022\004.TId\032\014.TPermission\"" +
      "\000\022E\n queryPermissionByRoleidAndAppKey\022\r." +
      "TIdAndString\032\020.ListTPermission\"\000\0223\n\027quer" +
      "yPermissionByRoleid\022\004.TId\032\020.ListTPermiss" +
      "ion\"\0002\210\001\n\017RoleGrpcService\022\033\n\tqueryById\022\004" +
      ".TId\032\006.TRole\"\000\0223\n\027queryPermissionByRolei" +
      "d\022\004.TId\032\020.ListTPermission\"\000\022#\n\rqueryByUs" +
      "erid\022\004.TId\032\n.ListTRole\"\000B:\n\034com.rrkj.flo" +
      "ur.authorize.apiB\025AuthorizeServiceProtoP" +
      "\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TPermission_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TPermission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TPermission_descriptor,
        new java.lang.String[] { "Id", "Name", "Ptype", "Permission", "Label", "Descr", "Utime", "Ctime", "Status", });
    internal_static_TRole_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TRole_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TRole_descriptor,
        new java.lang.String[] { "Id", "Name", "Title", "Icon", "Label", "Descr", "Utime", "Ctime", "Status", });
    internal_static_TId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_TIdAndString_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TIdAndString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TIdAndString_descriptor,
        new java.lang.String[] { "Id", "Str", });
    internal_static_ListTPermission_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ListTPermission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListTPermission_descriptor,
        new java.lang.String[] { "List", });
    internal_static_ListTRole_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ListTRole_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListTRole_descriptor,
        new java.lang.String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
