// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthorizeService.proto

package com.rrkj.flour.authorize.api;

public interface ListTRoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListTRole)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TRole list = 1;</code>
   */
  java.util.List<com.rrkj.flour.authorize.api.TRole> 
      getListList();
  /**
   * <code>repeated .TRole list = 1;</code>
   */
  com.rrkj.flour.authorize.api.TRole getList(int index);
  /**
   * <code>repeated .TRole list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .TRole list = 1;</code>
   */
  java.util.List<? extends com.rrkj.flour.authorize.api.TRoleOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .TRole list = 1;</code>
   */
  com.rrkj.flour.authorize.api.TRoleOrBuilder getListOrBuilder(
      int index);
}
