// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthorizeService.proto

package com.rrkj.flour.authorize.api;

public interface ListTPermissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListTPermission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TPermission list = 1;</code>
   */
  java.util.List<com.rrkj.flour.authorize.api.TPermission> 
      getListList();
  /**
   * <code>repeated .TPermission list = 1;</code>
   */
  com.rrkj.flour.authorize.api.TPermission getList(int index);
  /**
   * <code>repeated .TPermission list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .TPermission list = 1;</code>
   */
  java.util.List<? extends com.rrkj.flour.authorize.api.TPermissionOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .TPermission list = 1;</code>
   */
  com.rrkj.flour.authorize.api.TPermissionOrBuilder getListOrBuilder(
      int index);
}
