// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthorizeService.proto

package com.rrkj.flour.authorize.api;

/**
 * Protobuf service {@code PermissionGrpcService}
 */
public  abstract class PermissionGrpcService
    implements com.google.protobuf.Service {
  protected PermissionGrpcService() {}

  public interface Interface {
    /**
     * <code>rpc queryById(.TId) returns (.TPermission);</code>
     */
    public abstract void queryById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.TPermission> done);

    /**
     * <code>rpc queryPermissionByRoleidAndAppKey(.TIdAndString) returns (.ListTPermission);</code>
     */
    public abstract void queryPermissionByRoleidAndAppKey(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TIdAndString request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done);

    /**
     * <code>rpc queryPermissionByRoleid(.TId) returns (.ListTPermission);</code>
     */
    public abstract void queryPermissionByRoleid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new PermissionGrpcService() {
      @java.lang.Override
      public  void queryById(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.authorize.api.TId request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.TPermission> done) {
        impl.queryById(controller, request, done);
      }

      @java.lang.Override
      public  void queryPermissionByRoleidAndAppKey(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.authorize.api.TIdAndString request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done) {
        impl.queryPermissionByRoleidAndAppKey(controller, request, done);
      }

      @java.lang.Override
      public  void queryPermissionByRoleid(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.authorize.api.TId request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done) {
        impl.queryPermissionByRoleid(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.queryById(controller, (com.rrkj.flour.authorize.api.TId)request);
          case 1:
            return impl.queryPermissionByRoleidAndAppKey(controller, (com.rrkj.flour.authorize.api.TIdAndString)request);
          case 2:
            return impl.queryPermissionByRoleid(controller, (com.rrkj.flour.authorize.api.TId)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.rrkj.flour.authorize.api.TId.getDefaultInstance();
          case 1:
            return com.rrkj.flour.authorize.api.TIdAndString.getDefaultInstance();
          case 2:
            return com.rrkj.flour.authorize.api.TId.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.rrkj.flour.authorize.api.TPermission.getDefaultInstance();
          case 1:
            return com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance();
          case 2:
            return com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc queryById(.TId) returns (.TPermission);</code>
   */
  public abstract void queryById(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.authorize.api.TId request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.TPermission> done);

  /**
   * <code>rpc queryPermissionByRoleidAndAppKey(.TIdAndString) returns (.ListTPermission);</code>
   */
  public abstract void queryPermissionByRoleidAndAppKey(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.authorize.api.TIdAndString request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done);

  /**
   * <code>rpc queryPermissionByRoleid(.TId) returns (.ListTPermission);</code>
   */
  public abstract void queryPermissionByRoleid(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.authorize.api.TId request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.rrkj.flour.authorize.api.AuthorizeServiceProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.queryById(controller, (com.rrkj.flour.authorize.api.TId)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.authorize.api.TPermission>specializeCallback(
            done));
        return;
      case 1:
        this.queryPermissionByRoleidAndAppKey(controller, (com.rrkj.flour.authorize.api.TIdAndString)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.authorize.api.ListTPermission>specializeCallback(
            done));
        return;
      case 2:
        this.queryPermissionByRoleid(controller, (com.rrkj.flour.authorize.api.TId)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.authorize.api.ListTPermission>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.rrkj.flour.authorize.api.TId.getDefaultInstance();
      case 1:
        return com.rrkj.flour.authorize.api.TIdAndString.getDefaultInstance();
      case 2:
        return com.rrkj.flour.authorize.api.TId.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.rrkj.flour.authorize.api.TPermission.getDefaultInstance();
      case 1:
        return com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance();
      case 2:
        return com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.rrkj.flour.authorize.api.PermissionGrpcService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void queryById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.TPermission> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.rrkj.flour.authorize.api.TPermission.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.authorize.api.TPermission.class,
          com.rrkj.flour.authorize.api.TPermission.getDefaultInstance()));
    }

    public  void queryPermissionByRoleidAndAppKey(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TIdAndString request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.authorize.api.ListTPermission.class,
          com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance()));
    }

    public  void queryPermissionByRoleid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.authorize.api.ListTPermission> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.authorize.api.ListTPermission.class,
          com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.rrkj.flour.authorize.api.TPermission queryById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.authorize.api.ListTPermission queryPermissionByRoleidAndAppKey(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TIdAndString request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.authorize.api.ListTPermission queryPermissionByRoleid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.rrkj.flour.authorize.api.TPermission queryById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.authorize.api.TPermission) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.rrkj.flour.authorize.api.TPermission.getDefaultInstance());
    }


    public com.rrkj.flour.authorize.api.ListTPermission queryPermissionByRoleidAndAppKey(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TIdAndString request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.authorize.api.ListTPermission) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance());
    }


    public com.rrkj.flour.authorize.api.ListTPermission queryPermissionByRoleid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.authorize.api.TId request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.authorize.api.ListTPermission) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.rrkj.flour.authorize.api.ListTPermission.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:PermissionGrpcService)
}

