// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthorizeService.proto

package com.rrkj.flour.authorize.api;

public interface TIdAndStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TIdAndString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string str = 2;</code>
   */
  java.lang.String getStr();
  /**
   * <code>string str = 2;</code>
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
