// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

/**
 * Protobuf service {@code AccountGrpcService}
 */
public  abstract class AccountGrpcService
    implements com.google.protobuf.Service {
  protected AccountGrpcService() {}

  public interface Interface {
    /**
     * <code>rpc queryByUid(.TString) returns (.ListAccount);</code>
     */
    public abstract void queryByUid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TString request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done);

    /**
     * <code>rpc queryByUserid(.TId) returns (.ListAccount);</code>
     */
    public abstract void queryByUserid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done);

    /**
     * <code>rpc queryByUseridAndType(.TUseridAndType) returns (.ListAccount);</code>
     */
    public abstract void queryByUseridAndType(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TUseridAndType request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done);

    /**
     * <code>rpc create(.TAccount) returns (.TAccount);</code>
     */
    public abstract void create(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done);

    /**
     * <code>rpc update(.TAccount) returns (.TAccount);</code>
     */
    public abstract void update(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done);

    /**
     * <code>rpc removeById(.TId) returns (.TRBool);</code>
     */
    public abstract void removeById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TRBool> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new AccountGrpcService() {
      @java.lang.Override
      public  void queryByUid(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.user.api.TString request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done) {
        impl.queryByUid(controller, request, done);
      }

      @java.lang.Override
      public  void queryByUserid(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.user.api.TId request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done) {
        impl.queryByUserid(controller, request, done);
      }

      @java.lang.Override
      public  void queryByUseridAndType(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.user.api.TUseridAndType request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done) {
        impl.queryByUseridAndType(controller, request, done);
      }

      @java.lang.Override
      public  void create(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.user.api.TAccount request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done) {
        impl.create(controller, request, done);
      }

      @java.lang.Override
      public  void update(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.user.api.TAccount request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done) {
        impl.update(controller, request, done);
      }

      @java.lang.Override
      public  void removeById(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.user.api.TId request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TRBool> done) {
        impl.removeById(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.queryByUid(controller, (com.rrkj.flour.user.api.TString)request);
          case 1:
            return impl.queryByUserid(controller, (com.rrkj.flour.user.api.TId)request);
          case 2:
            return impl.queryByUseridAndType(controller, (com.rrkj.flour.user.api.TUseridAndType)request);
          case 3:
            return impl.create(controller, (com.rrkj.flour.user.api.TAccount)request);
          case 4:
            return impl.update(controller, (com.rrkj.flour.user.api.TAccount)request);
          case 5:
            return impl.removeById(controller, (com.rrkj.flour.user.api.TId)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.rrkj.flour.user.api.TString.getDefaultInstance();
          case 1:
            return com.rrkj.flour.user.api.TId.getDefaultInstance();
          case 2:
            return com.rrkj.flour.user.api.TUseridAndType.getDefaultInstance();
          case 3:
            return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
          case 4:
            return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
          case 5:
            return com.rrkj.flour.user.api.TId.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.rrkj.flour.user.api.ListAccount.getDefaultInstance();
          case 1:
            return com.rrkj.flour.user.api.ListAccount.getDefaultInstance();
          case 2:
            return com.rrkj.flour.user.api.ListAccount.getDefaultInstance();
          case 3:
            return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
          case 4:
            return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
          case 5:
            return com.rrkj.flour.user.api.TRBool.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc queryByUid(.TString) returns (.ListAccount);</code>
   */
  public abstract void queryByUid(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.user.api.TString request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done);

  /**
   * <code>rpc queryByUserid(.TId) returns (.ListAccount);</code>
   */
  public abstract void queryByUserid(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.user.api.TId request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done);

  /**
   * <code>rpc queryByUseridAndType(.TUseridAndType) returns (.ListAccount);</code>
   */
  public abstract void queryByUseridAndType(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.user.api.TUseridAndType request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done);

  /**
   * <code>rpc create(.TAccount) returns (.TAccount);</code>
   */
  public abstract void create(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.user.api.TAccount request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done);

  /**
   * <code>rpc update(.TAccount) returns (.TAccount);</code>
   */
  public abstract void update(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.user.api.TAccount request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done);

  /**
   * <code>rpc removeById(.TId) returns (.TRBool);</code>
   */
  public abstract void removeById(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.user.api.TId request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TRBool> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.rrkj.flour.user.api.UserServiceProto.getDescriptor().getServices().get(1);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.queryByUid(controller, (com.rrkj.flour.user.api.TString)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.user.api.ListAccount>specializeCallback(
            done));
        return;
      case 1:
        this.queryByUserid(controller, (com.rrkj.flour.user.api.TId)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.user.api.ListAccount>specializeCallback(
            done));
        return;
      case 2:
        this.queryByUseridAndType(controller, (com.rrkj.flour.user.api.TUseridAndType)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.user.api.ListAccount>specializeCallback(
            done));
        return;
      case 3:
        this.create(controller, (com.rrkj.flour.user.api.TAccount)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.user.api.TAccount>specializeCallback(
            done));
        return;
      case 4:
        this.update(controller, (com.rrkj.flour.user.api.TAccount)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.user.api.TAccount>specializeCallback(
            done));
        return;
      case 5:
        this.removeById(controller, (com.rrkj.flour.user.api.TId)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.user.api.TRBool>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.rrkj.flour.user.api.TString.getDefaultInstance();
      case 1:
        return com.rrkj.flour.user.api.TId.getDefaultInstance();
      case 2:
        return com.rrkj.flour.user.api.TUseridAndType.getDefaultInstance();
      case 3:
        return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
      case 4:
        return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
      case 5:
        return com.rrkj.flour.user.api.TId.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.rrkj.flour.user.api.ListAccount.getDefaultInstance();
      case 1:
        return com.rrkj.flour.user.api.ListAccount.getDefaultInstance();
      case 2:
        return com.rrkj.flour.user.api.ListAccount.getDefaultInstance();
      case 3:
        return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
      case 4:
        return com.rrkj.flour.user.api.TAccount.getDefaultInstance();
      case 5:
        return com.rrkj.flour.user.api.TRBool.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.rrkj.flour.user.api.AccountGrpcService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void queryByUid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TString request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.rrkj.flour.user.api.ListAccount.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.user.api.ListAccount.class,
          com.rrkj.flour.user.api.ListAccount.getDefaultInstance()));
    }

    public  void queryByUserid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.rrkj.flour.user.api.ListAccount.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.user.api.ListAccount.class,
          com.rrkj.flour.user.api.ListAccount.getDefaultInstance()));
    }

    public  void queryByUseridAndType(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TUseridAndType request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.ListAccount> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.rrkj.flour.user.api.ListAccount.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.user.api.ListAccount.class,
          com.rrkj.flour.user.api.ListAccount.getDefaultInstance()));
    }

    public  void create(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.rrkj.flour.user.api.TAccount.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.user.api.TAccount.class,
          com.rrkj.flour.user.api.TAccount.getDefaultInstance()));
    }

    public  void update(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TAccount> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        com.rrkj.flour.user.api.TAccount.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.user.api.TAccount.class,
          com.rrkj.flour.user.api.TAccount.getDefaultInstance()));
    }

    public  void removeById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.user.api.TRBool> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        com.rrkj.flour.user.api.TRBool.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.user.api.TRBool.class,
          com.rrkj.flour.user.api.TRBool.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.rrkj.flour.user.api.ListAccount queryByUid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TString request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.user.api.ListAccount queryByUserid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.user.api.ListAccount queryByUseridAndType(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TUseridAndType request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.user.api.TAccount create(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.user.api.TAccount update(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.user.api.TRBool removeById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.rrkj.flour.user.api.ListAccount queryByUid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TString request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.user.api.ListAccount) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.rrkj.flour.user.api.ListAccount.getDefaultInstance());
    }


    public com.rrkj.flour.user.api.ListAccount queryByUserid(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.user.api.ListAccount) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.rrkj.flour.user.api.ListAccount.getDefaultInstance());
    }


    public com.rrkj.flour.user.api.ListAccount queryByUseridAndType(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TUseridAndType request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.user.api.ListAccount) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.rrkj.flour.user.api.ListAccount.getDefaultInstance());
    }


    public com.rrkj.flour.user.api.TAccount create(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.user.api.TAccount) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.rrkj.flour.user.api.TAccount.getDefaultInstance());
    }


    public com.rrkj.flour.user.api.TAccount update(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TAccount request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.user.api.TAccount) channel.callBlockingMethod(
        getDescriptor().getMethods().get(4),
        controller,
        request,
        com.rrkj.flour.user.api.TAccount.getDefaultInstance());
    }


    public com.rrkj.flour.user.api.TRBool removeById(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.user.api.TId request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.user.api.TRBool) channel.callBlockingMethod(
        getDescriptor().getMethods().get(5),
        controller,
        request,
        com.rrkj.flour.user.api.TRBool.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:AccountGrpcService)
}

