// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

public interface ListUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TUser list = 1;</code>
   */
  java.util.List<com.rrkj.flour.user.api.TUser> 
      getListList();
  /**
   * <code>repeated .TUser list = 1;</code>
   */
  com.rrkj.flour.user.api.TUser getList(int index);
  /**
   * <code>repeated .TUser list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .TUser list = 1;</code>
   */
  java.util.List<? extends com.rrkj.flour.user.api.TUserOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .TUser list = 1;</code>
   */
  com.rrkj.flour.user.api.TUserOrBuilder getListOrBuilder(
      int index);
}
