// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

public interface ListAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .TAccount list = 1;</code>
   */
  java.util.List<com.rrkj.flour.user.api.TAccount> 
      getListList();
  /**
   * <code>repeated .TAccount list = 1;</code>
   */
  com.rrkj.flour.user.api.TAccount getList(int index);
  /**
   * <code>repeated .TAccount list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .TAccount list = 1;</code>
   */
  java.util.List<? extends com.rrkj.flour.user.api.TAccountOrBuilder> 
      getListOrBuilderList();
  /**
   * <code>repeated .TAccount list = 1;</code>
   */
  com.rrkj.flour.user.api.TAccountOrBuilder getListOrBuilder(
      int index);
}
