// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

public interface TAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string openid = 2;</code>
   */
  java.lang.String getOpenid();
  /**
   * <code>string openid = 2;</code>
   */
  com.google.protobuf.ByteString
      getOpenidBytes();

  /**
   * <code>string type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string uuid = 4;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 4;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string label = 5;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 5;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>int32 status = 6;</code>
   */
  int getStatus();

  /**
   * <code>int64 userid = 7;</code>
   */
  long getUserid();

  /**
   * <code>.TUser user = 8;</code>
   */
  boolean hasUser();
  /**
   * <code>.TUser user = 8;</code>
   */
  com.rrkj.flour.user.api.TUser getUser();
  /**
   * <code>.TUser user = 8;</code>
   */
  com.rrkj.flour.user.api.TUserOrBuilder getUserOrBuilder();

  /**
   * <code>int64 ctime = 9;</code>
   */
  long getCtime();

  /**
   * <code>int64 utime = 10;</code>
   */
  long getUtime();
}
