// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

public interface TNameAndLabelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TNameAndLabel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string label = 2;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 2;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
