// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

public interface TRBoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TRBool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool res = 1;</code>
   */
  boolean getRes();
}
