// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

public interface TUseridAndTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TUseridAndType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userid = 1;</code>
   */
  long getUserid();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
