// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.rrkj.flour.user.api;

public interface TUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string nickname = 3;</code>
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 3;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string uid = 5;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 5;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string icon = 6;</code>
   */
  java.lang.String getIcon();
  /**
   * <code>string icon = 6;</code>
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>string phone = 7;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 7;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string email = 8;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 8;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string birthday = 9;</code>
   */
  java.lang.String getBirthday();
  /**
   * <code>string birthday = 9;</code>
   */
  com.google.protobuf.ByteString
      getBirthdayBytes();

  /**
   * <code>.TUser.GenderType gender = 10;</code>
   */
  int getGenderValue();
  /**
   * <code>.TUser.GenderType gender = 10;</code>
   */
  com.rrkj.flour.user.api.TUser.GenderType getGender();

  /**
   * <code>string label = 11;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 11;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>int32 status = 12;</code>
   */
  int getStatus();

  /**
   * <code>int64 utime = 13;</code>
   */
  long getUtime();

  /**
   * <code>int64 ctime = 14;</code>
   */
  long getCtime();
}
