// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oauth2Service.proto

package com.rrkj.flour.oauth2.api;

/**
 * Protobuf service {@code LoginGrpcService}
 */
public  abstract class LoginGrpcService
    implements com.google.protobuf.Service {
  protected LoginGrpcService() {}

  public interface Interface {
    /**
     * <code>rpc checkAccessToken(.TString) returns (.TLoginResponse);</code>
     */
    public abstract void checkAccessToken(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.TString request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done);

    /**
     * <code>rpc login(.LoginRequest) returns (.TLoginResponse);</code>
     */
    public abstract void login(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.LoginRequest request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new LoginGrpcService() {
      @java.lang.Override
      public  void checkAccessToken(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.oauth2.api.TString request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done) {
        impl.checkAccessToken(controller, request, done);
      }

      @java.lang.Override
      public  void login(
          com.google.protobuf.RpcController controller,
          com.rrkj.flour.oauth2.api.LoginRequest request,
          com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done) {
        impl.login(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.checkAccessToken(controller, (com.rrkj.flour.oauth2.api.TString)request);
          case 1:
            return impl.login(controller, (com.rrkj.flour.oauth2.api.LoginRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.rrkj.flour.oauth2.api.TString.getDefaultInstance();
          case 1:
            return com.rrkj.flour.oauth2.api.LoginRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance();
          case 1:
            return com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc checkAccessToken(.TString) returns (.TLoginResponse);</code>
   */
  public abstract void checkAccessToken(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.oauth2.api.TString request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done);

  /**
   * <code>rpc login(.LoginRequest) returns (.TLoginResponse);</code>
   */
  public abstract void login(
      com.google.protobuf.RpcController controller,
      com.rrkj.flour.oauth2.api.LoginRequest request,
      com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.rrkj.flour.oauth2.api.Oauth2ServiceProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.checkAccessToken(controller, (com.rrkj.flour.oauth2.api.TString)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.oauth2.api.TLoginResponse>specializeCallback(
            done));
        return;
      case 1:
        this.login(controller, (com.rrkj.flour.oauth2.api.LoginRequest)request,
          com.google.protobuf.RpcUtil.<com.rrkj.flour.oauth2.api.TLoginResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.rrkj.flour.oauth2.api.TString.getDefaultInstance();
      case 1:
        return com.rrkj.flour.oauth2.api.LoginRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance();
      case 1:
        return com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.rrkj.flour.oauth2.api.LoginGrpcService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void checkAccessToken(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.TString request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.oauth2.api.TLoginResponse.class,
          com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance()));
    }

    public  void login(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.LoginRequest request,
        com.google.protobuf.RpcCallback<com.rrkj.flour.oauth2.api.TLoginResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.rrkj.flour.oauth2.api.TLoginResponse.class,
          com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.rrkj.flour.oauth2.api.TLoginResponse checkAccessToken(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.TString request)
        throws com.google.protobuf.ServiceException;

    public com.rrkj.flour.oauth2.api.TLoginResponse login(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.LoginRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.rrkj.flour.oauth2.api.TLoginResponse checkAccessToken(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.TString request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.oauth2.api.TLoginResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance());
    }


    public com.rrkj.flour.oauth2.api.TLoginResponse login(
        com.google.protobuf.RpcController controller,
        com.rrkj.flour.oauth2.api.LoginRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.rrkj.flour.oauth2.api.TLoginResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.rrkj.flour.oauth2.api.TLoginResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:LoginGrpcService)
}

