// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oauth2Service.proto

package com.rrkj.flour.oauth2.api;

public interface TLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TLoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string accessToken = 3;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <code>string accessToken = 3;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>int64 userid = 4;</code>
   */
  long getUserid();

  /**
   * <code>string username = 5;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 5;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>map&lt;string, string&gt; data = 6;</code>
   */
  int getDataCount();
  /**
   * <code>map&lt;string, string&gt; data = 6;</code>
   */
  boolean containsData(
      java.lang.String key);
  /**
   * Use {@link #getDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getData();
  /**
   * <code>map&lt;string, string&gt; data = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDataMap();
  /**
   * <code>map&lt;string, string&gt; data = 6;</code>
   */

  java.lang.String getDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; data = 6;</code>
   */

  java.lang.String getDataOrThrow(
      java.lang.String key);
}
