// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Oauth2Service.proto

package com.rrkj.flour.oauth2.api;

public interface TStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 1;</code>
   */
  java.lang.String getStr();
  /**
   * <code>string str = 1;</code>
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
